function [p0] = tire_model_est(States_matrix_front,States_matrix_rear)
%Estimation of tire-force model for use in individual tire force
%calculations
%States_matrix = [alpha,F_normal,F_lateral,s,F_longitudinal]
%p0 = [B C D E]
%y = Dsin(C.atan(B.x-E.(B.X-atan(B.x)), x= alpha or slip ratio, y= Fx/Fn or Fy/Fn
k = 0;
p0.front_y = [10, 1.9, 1, 0.97];
p0.front_x = [10, 1.9, 1, 0.97];
p0.rear_y = [10, 1.9, 1, 0.97];
p0.rear_x = [10, 1.9, 1, 0.97];

f_tire.front_y(k) = States_matrix_front(2)*p0.front_y(3)*sin(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))));
f_tire.rear_y(k) = States_matrix_rear(2)*p0.rear_y(3)*sin(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))));

f_tire.front_x(k) = States_matrix_front(2)*p0.front_x(3)*sin(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))));
f_tire.rear_x(k) = States_matrix_rear(2)*p0.rear_x(3)*sin(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))));

tol = 1e-3;

%% Front wheel lateral force tyre-model estimation %%
J_p_front_y(1) = (States_matrix_front(2)*p0.front_y(3))*cos(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))))*p0.front_y(2)/(1+(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1)))^2)*((1-p0.front_y(4))*States_matrix_front(1)+p0.front_y(4)/(1 + ...
    (p0.front_y(1)*States_matrix_front(1))^2)*States_matrix_front(1));
J_p_front_y(2) = (States_matrix_front(2)*p0.front_y(3))*cos(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))))*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1)));
J_p_front_y(3) = States_matrix_front(2)*sin(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))));
J_p_front_y(4) = (States_matrix_front(2)*p0.front_y(3))*cos(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))))*p0.front_y(2)/(1+(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1)))^2)*(-p0.front_y(1)*States_matrix_front(1)+atan(p0.front_y(1)*States_matrix_front(1)));
del_front_y = -(transpose(J_p_front_y)*J_p_front_y)^(-1)*transpose(J_p_front_y)*(f_tire.front_y(k)-States_matrix_front(3));
a = 0.5;
k = k+1;
p0.front_y = p0.front_y + del_front_y;
f_tire.front_y(k) = States_matrix_front(2)*p0.front_y(3)*sin(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))));

while abs(f_tire.front_y(k-1)-States_matrix_front(3))-abs(f_tire.front_y(k)-States_matrix_front(3)) >= tol
    J_p_front_y(1) = (States_matrix_front(2)*p0.front_y(3))*cos(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))))*p0.front_y(2)/(1+(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1)))^2)*((1-p0.front_y(4))*States_matrix_front(1)+p0.front_y(4)/(1 + ...
    (p0.front_y(1)*States_matrix_front(1))^2)*States_matrix_front(1));
    J_p_front_y(2) = (States_matrix_front(2)*p0.front_y(3))*cos(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))))*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1)));
    J_p_front_y(3) = States_matrix_front(2)*sin(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))));
    J_p_front_y(4) = (States_matrix_front(2)*p0.front_y(3))*cos(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))))*p0.front_y(2)/(1+(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1)))^2)*(-p0.front_y(1)*States_matrix_front(1)+atan(p0.front_y(1)*States_matrix_front(1)));
    del_front_y = -(transpose(J_p_front_y)*J_p_front_y)^(-1)*transpose(J_p_front_y)*(f_tire.front_y(k)-States_matrix_front(3)); 
    a = 0.5;
    k = k+1;
    p0.front_y = p0.front_y + del_front_y;
    f_tire.front_y(k) = States_matrix_front(2)*p0.front_y(3)*sin(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
    p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))));
    while abs(f_tire.front_y(k-1)-States_matrix_front(3)) <= abs(f_tire.front_y(k)-States_matrix_front(3))
        del_front_y = a*del_front_y;
        p0.front_y = p0.front_y + del_front_y;
        f_tire.front_y(k) = States_matrix_front(2)*p0.front_y(3)*sin(p0.front_y(2)*atan(p0.front_y(1)*(1-p0.front_y(4))*States_matrix_front(1) + ...
        p0.front_y(4)*atan(p0.front_y(1)*States_matrix_front(1))));
    end
end

k = 0;


%% Rear wheel lateral force tyre-model estimation %%
J_p_rear_y(1) = (States_matrix_rear(2)*p0.rear_y(3))*cos(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))))*p0.rear_y(2)/(1+(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1)))^2)*((1-p0.rear_y(4))*States_matrix_rear(1)+p0.rear_y(4)/(1 + ...
    (p0.rear_y(1)*States_matrix_rear(1))^2)*States_matrix_rear(1));
J_p_rear_y(2) = (States_matrix_rear(2)*p0.rear_y(3))*cos(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))))*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1)));
J_p_rear_y(3) = States_matrix_rear(2)*sin(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))));
J_p_rear_y(4) = (States_matrix_rear(2)*p0.rear_y(3))*cos(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))))*p0.rear_y(2)/(1+(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1)))^2)*(-p0.rear_y(1)*States_matrix_rear(1)+atan(p0.rear_y(1)*States_matrix_rear(1)));



del_rear_y = -(transpose(J_p_rear_y)*J_p_rear_y)^(-1)*transpose(J_p_rear_y)*(f_tire.rear_y(k)-States_matrix_rear(3));
a = 0.5;
k = k+1;
p0.rear_y = p0.rear_y + del_rear_y;
f_tire.rear_y(k) = States_matrix_rear(2)*p0.rear_y(3)*sin(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))));

while abs(f_tire.rear_y(k-1)-States_matrix_rear(3))-abs(f_tire.rear_y(k)-States_matrix_rear(3)) >= tol
    J_p_rear_y(1) = (States_matrix_rear(2)*p0.rear_y(3))*cos(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))))*p0.rear_y(2)/(1+(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1)))^2)*((1-p0.rear_y(4))*States_matrix_rear(1)+p0.rear_y(4)/(1 + ...
    (p0.rear_y(1)*States_matrix_rear(1))^2)*States_matrix_rear(1));
    J_p_rear_y(2) = (States_matrix_rear(2)*p0.rear_y(3))*cos(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))))*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1)));
    J_p_rear_y(3) = States_matrix_rear(2)*sin(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))));
    J_p_rear_y(4) = (States_matrix_rear(2)*p0.rear_y(3))*cos(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))))*p0.rear_y(2)/(1+(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1)))^2)*(-p0.rear_y(1)*States_matrix_rear(1)+atan(p0.rear_y(1)*States_matrix_rear(1)));
    del_rear_y = -(transpose(J_p_rear_y)*J_p_rear_y)^(-1)*transpose(J_p_rear_y)*(f_tire.rear_y(k)-States_matrix_rear(3));
    a = 0.5;
    k = k+1;
    p0.rear_y = p0.rear_y + del_rear_y;
    f_tire.rear_y(k) = States_matrix_rear(2)*p0.rear_y(3)*sin(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
    p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))));


    while abs(f_tire.rear_y(k-1)-States_matrix_rear(3)) <= abs(f_tire.rear_y(k)-States_matrix_rear(3))
        del_rear_y = a*del_rear_y;
        p0.rear_y = p0.rear_y + del_rear_y;
        f_tire.rear_y(k) = States_matrix_rear(2)*p0.rear_y(3)*sin(p0.rear_y(2)*atan(p0.rear_y(1)*(1-p0.rear_y(4))*States_matrix_rear(1) + ...
        p0.rear_y(4)*atan(p0.rear_y(1)*States_matrix_rear(1))));
    end
end




k = 0;
%% Front wheel longitudinal force tyre-model estimation %%

J_p_front_x(1) = (States_matrix_front(2)*p0.front_x(3))*cos(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))))*p0.front_x(2)/(1+(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4)))^2)*((1-p0.front_x(4))*States_matrix_front(4)+p0.front_x(4)/(1 + ...
    (p0.front_x(1)*States_matrix_front(4))^2)*States_matrix_front(4));
J_p_front_x(2) = (States_matrix_front(2)*p0.front_x(3))*cos(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))))*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4)));
J_p_front_x(3) = States_matrix_front(2)*sin(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))));
J_p_front_x(4) = (States_matrix_front(2)*p0.front_x(3))*cos(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))))*p0.front_x(2)/(1+(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4)))^2)*(-p0.front_x(1)*States_matrix_front(4)+atan(p0.front_x(1)*States_matrix_front(4)));
del_front_x = -(transpose(J_p_front_x)*J_p_front_x)^(-1)*transpose(J_p_front_x)*(f_tire.front_x(k)-States_matrix_front(5));
a = 0.5;
k = k+1;
p0.front_x = p0.front_x + del_front_x;
f_tire.front_x(k) = States_matrix_front(2)*p0.front_x(3)*sin(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))));

while abs(f_tire.front_x(k-1)-States_matrix_front(5))-abs(f_tire.front_x(k)-States_matrix_front(5)) >= tol
    J_p_front_x(1) = (States_matrix_front(2)*p0.front_x(3))*cos(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))))*p0.front_x(2)/(1+(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4)))^2)*((1-p0.front_x(4))*States_matrix_front(4)+p0.front_x(4)/(1 + ...
    (p0.front_x(1)*States_matrix_front(4))^2)*States_matrix_front(4));
J_p_front_x(2) = (States_matrix_front(2)*p0.front_x(3))*cos(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))))*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4)));
J_p_front_x(3) = States_matrix_front(2)*sin(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))));
J_p_front_x(4) = (States_matrix_front(2)*p0.front_x(3))*cos(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))))*p0.front_x(2)/(1+(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4)))^2)*(-p0.front_x(1)*States_matrix_front(4)+atan(p0.front_x(1)*States_matrix_front(4)));
    del_front_x = -(transpose(J_p_front_x)*J_p_front_x)^(-1)*transpose(J_p_front_x)*(f_tire.front_x(k)-States_matrix_front(5));
    a = 0.5;
    k = k+1;
    p0.front_x = p0.front_x + del_front_x;
    f_tire.front_x(k) = States_matrix_front(2)*p0.front_x(3)*sin(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
    p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))));

    while abs(f_tire.front_x(k-1)-States_matrix_front(5)) <= abs(f_tire.front_x(k)-States_matrix_front(5))
        del_front_x = a*del_front_x;
        p0.front_x = p0.front_x + del_front_x;
        f_tire.front_x(k) = States_matrix_front(2)*p0.front_x(3)*sin(p0.front_x(2)*atan(p0.front_x(1)*(1-p0.front_x(4))*States_matrix_front(4) + ...
            p0.front_x(4)*atan(p0.front_x(1)*States_matrix_front(4))));
    end
end

k = 0;
%% Rear wheel longitudinal force tyre-model estimation %%
J_p_rear_x(1) = (States_matrix_rear(2)*p0.rear_x(3))*cos(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))))*p0.rear_x(2)/(1+(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4)))^2)*((1-p0.rear_x(4))*States_matrix_rear(4)+p0.rear_x(4)/(1 + ...
    (p0.rear_x(1)*States_matrix_rear(4))^2)*States_matrix_rear(4));
J_p_rear_x(2) = (States_matrix_rear(2)*p0.rear_x(3))*cos(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))))*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4)));
J_p_rear_x(3) = States_matrix_rear(2)*sin(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))));
J_p_rear_x(4) = (States_matrix_rear(2)*p0.rear_x(3))*cos(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))))*p0.rear_x(2)/(1+(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4)))^2)*(-p0.rear_x(1)*States_matrix_rear(4)+atan(p0.rear_x(1)*States_matrix_rear(4)));
del_rear_x = -(transpose(J_p_rear_x)*J_p_rear_x)^(-1)*transpose(J_p_rear_x)*(f_tire.rear_x(k)-States_matrix_rear(5));
a = 0.5;
k = k+1;
p0.rear_x = p0.rear_x + del_rear_x;
f_tire.rear_x(k) = States_matrix_rear(2)*p0.rear_x(3)*sin(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))));

while abs(f_tire.rear_x(k-1)-States_matrix_rear(5))-abs(f_tire.rear_x(k)-States_matrix_rear(5)) >= tol
    J_p_rear_x(1) = (States_matrix_rear(2)*p0.rear_x(3))*cos(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))))*p0.rear_x(2)/(1+(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4)))^2)*((1-p0.rear_x(4))*States_matrix_rear(4)+p0.rear_x(4)/(1 + ...
    (p0.rear_x(1)*States_matrix_rear(4))^2)*States_matrix_rear(4));
J_p_rear_x(2) = (States_matrix_rear(2)*p0.rear_x(3))*cos(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))))*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4)));
J_p_rear_x(3) = States_matrix_rear(2)*sin(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))));
J_p_rear_x(4) = (States_matrix_rear(2)*p0.rear_x(3))*cos(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))))*p0.rear_x(2)/(1+(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4)))^2)*(-p0.rear_x(1)*States_matrix_rear(4)+atan(p0.rear_x(1)*States_matrix_rear(4)));
    del_rear_x = -(transpose(J_p_rear_x)*J_p_rear_x)^(-1)*transpose(J_p_rear_x)*(f_tire.rear_x(k)-States_matrix_rear(5));
    a = 0.5;
    k = k+1;
    p0.rear_x = p0.rear_x + del_rear_x;
    f_tire.rear_x(k) = States_matrix_rear(2)*p0.rear_x(3)*sin(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
    p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))));

    while abs(f_tire.rear_x(k-1)-States_matrix_rear(5)) <= abs(f_tire.rear_x(k)-States_matrix_rear(5))
        del_rear_x = a*del_rear_x;
        p0.rear_x = p0.rear_x + del_rear_x;
        f_tire.rear_x(k) = States_matrix_rear(2)*p0.rear_x(3)*sin(p0.rear_x(2)*atan(p0.rear_x(1)*(1-p0.rear_x(4))*States_matrix_rear(4) + ...
        p0.rear_x(4)*atan(p0.rear_x(1)*States_matrix_rear(4))));
    end
end

end

